CREATE TABLE CLIENTE (
    ID_CLIENTE INTEGER NOT NULL,
    NOME VARCHAR(100),
    CPF VARCHAR(11),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE CARRO (
    ID_CARRO INTEGER NOT NULL,
    MODELO VARCHAR(50),
    DATA_LANCAMENTO DATE,
    CONSTRAINT PK_CARRO PRIMARY KEY (ID_CARRO)
);

CREATE TABLE VENDA (
    ID_VENDA INTEGER NOT NULL,
    ID_CLIENTE INTEGER,
    ID_CARRO INTEGER,
    DATA_VENDA DATE,
    CONSTRAINT PK_VENDA PRIMARY KEY (ID_VENDA),

    CONSTRAINT FK_VENDA_CLIENTE
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTE(ID_CLIENTE),

    CONSTRAINT FK_VENDA_CARRO
        FOREIGN KEY (ID_CARRO)
        REFERENCES CARRO(ID_CARRO)
);