SELECT
    CL.NOME,
    COUNT(*) AS QTDE_UNO
FROM VENDA V
JOIN CLIENTE CL
    ON CL.ID_CLIENTE = V.ID_CLIENTE
JOIN CARRO C
    ON C.ID_CARRO = V.ID_CARRO
WHERE C.MODELO = 'UNO'
GROUP BY CL.NOME
ORDER BY QTDE_UNO DESC;