SELECT FIRST 15
    CL.ID_CLIENTE,
    CL.NOME,
    CL.CPF,
    V.DATA_VENDA
FROM CLIENTE CL

JOIN VENDA V
    ON V.ID_CLIENTE = CL.ID_CLIENTE

JOIN CARRO C
    ON C.ID_CARRO = V.ID_CARRO

WHERE
    CL.CPF STARTING WITH '0'
    AND EXTRACT(YEAR FROM C.DATA_LANCAMENTO) = 2021

    AND CL.ID_CLIENTE NOT IN (
        SELECT
            V2.ID_CLIENTE
        FROM VENDA V2
        JOIN CARRO C2
            ON C2.ID_CARRO = V2.ID_CARRO
        WHERE C2.MODELO = 'MAREA'
        GROUP BY V2.ID_CLIENTE
        HAVING COUNT(*) >= 2
    )

ORDER BY V.DATA_VENDA;