DELETE FROM VENDA V
WHERE NOT EXISTS (

    SELECT 1
    FROM CLIENTE CL

    JOIN CARRO C
        ON C.ID_CARRO = V.ID_CARRO

    WHERE
        CL.ID_CLIENTE = V.ID_CLIENTE
        AND CL.CPF STARTING WITH '0'
        AND EXTRACT(YEAR FROM C.DATA_LANCAMENTO) = 2021
);