CREATE TABLE PRODUTOREGRA (
    ID_PRODUTOREGRA INTEGER NOT NULL,
    DESCRICAO VARCHAR(100),

    CONSTRAINT PK_PRODUTOREGRA
    PRIMARY KEY (ID_PRODUTOREGRA)
);

CREATE TABLE PRODUTO (
    ID_PRODUTO INTEGER NOT NULL,
    DESCRICAO VARCHAR(100),
    ID_PRODUTOREGRA INTEGER,

    CONSTRAINT PK_PRODUTO
    PRIMARY KEY (ID_PRODUTO),

    CONSTRAINT FK_PRODUTO_REGRA
    FOREIGN KEY (ID_PRODUTOREGRA)
    REFERENCES PRODUTOREGRA(ID_PRODUTOREGRA)
);